### ISSUE TITLE
Additional concerns for Journal Entry n°1 - Event Processing

### ISSUE THREAD

**Issue by tomkerkhove** [MicrosoftArchive/iot-journey#172]
> DISCLAIMER - These comments are based on the DRAFT version and I apologize if the feedback is false because of the DRAFT status 

I've read the current draft of journal entry 1 and have some additional **concerns** I have that you might consider : 
### Service Bus Topic & Worker Roles
- **Security / Device Management** - You don't have granular control over the authentication for the sending parties. If you want to revoke access to one specific device, you'll need to revoke the complete policy since you can only create a limited amount of these resulting in revoking others.
- **Connectivity** - The number of concurrent brokered connections (AMQP) is limited to 5k, additional connection requests will be rejected. With 100k devices in scope this will be an issue. _(Upgrading to Standard-tier namespace won't fix that at first sight)_

I might be wrong on the concurrent calls but saw it in the [Service Bus Quotas](https://msdn.microsoft.com/en-us/library/azure/ee732538.aspx) so it's something to keep in mind.
### Azure Event Hubs & Azure Stream Analytics
- **Querying Language** - You're stuck to the ASA syntax, are there features in the language we lack at the moment? There is also no extensibility available yet although this is not a concern at the moment I guess?
### Storm comparison?

In the last call @bennage mentioned that there was an experiment with a storm cluster, are there plans to include this to the comparison list as well?
### Payload format comparison?

In the selected technologies it says that you've chosen to use JSON, are there plans to do a comparison between other formats as well? Or was this a no-brainer for the interoperability? I'm just thinking about i.e. BSON.

Relates to #51 & #117.

**Comment by tomkerkhove** [comment]
Yet the current DRAFT is already very helpful to follow your technology considerations.

**Comment by bennage** [comment]
This is great feedback. I'd like to invite others to add their feedback as well.

**Comment by tomkerkhove** [comment]
Closing as the repo is archived
