### ISSUE TITLE
Guidance on device protocols

### ISSUE THREAD

**Issue by tomkerkhove** [MicrosoftArchive/iot-journey#196]
I was wondering if this project will also provide guidance on what protocols you can use to communicate for device -> Field Gateway -> Cloud?

When the device is capable you should use AMQP but what if it's not? What is the most secure protocol to use? I don't want someone eavesdropping or sending his own malicious data.

This is probably something that is out of scope or not?

Relates to #194.

**Comment by ppatierno** [comment]
I suppose that it is out of scope of this project ... however ... I love protocols dissertation so ... :-)

All Microsoft Azure services (like Service Bus with Event Hubs and so on) are based on AMQP (or HTTP with RESTful APIs). AMQP isn't born for IoT (of course) but for connecting enterprise applications. It has a lot of features and supported patterns that in most cases are too much for a local sensors network. Today, current devices in industrial or home space use other protocols like OPC-UA, Modbus, BACnet and over them ZigBee, Z-Wave or Ethernet/WiFi of course. In this case, the field gateway (to connect Azure) needs to bridge from these protocols to AMQP and vice versa. In most new environments, some devices connected using Ethernet/WiFi can use MQTT or CoAP that are lighter than AMQP. Of course, it's related to devices capabilities (and their contraints). Other solution could be AllJoyn and/or Thread (see last news from Microsoft).
Ragarding security in local communication with constrained devices, it's more expensive to have protocols like SSL/TLS and you can use simple payload encryption or hashing (depending if you want confidentiality or integrity or both).

**Comment by tomkerkhove** [comment]
My point exactly and as security is important it might be interesting to discuss device to field gateway communication so that people ask the right questions and maybe even propose a suggested protocol for non-TLS/AMQP enabled devices

**Comment by bennage** [comment]
We did have something similiar on the backlog (see #3), the reasons why we are not currently pursuing it are discussed there. Nevertheless, I would think having a public conversation, even if it doesn't result in prescriptive guidance, is valuable.

One approach that I was considering is to discuss principles and characteristics of protocosl, without diving into how they map to specific protocols.

**Comment by tomkerkhove** [comment]
My personal issue is that I'm more a cloud Developer and have no knowledge of when I should use protocol A over protocol B but it makes total sense, thanks for the clafication

**Comment by ppatierno** [comment]
Howerver on #3 I read the following : 

"It's more likely that people are interested in how to make different protocols work together (e.g. protocol translation)"

So IMHO it's important to write a document about this.

**Comment by bennage** [comment]
That's the goal of #195. I'd love to have more input there on what questions and challenges would are facing.

**Comment by tomkerkhove** [comment]
Closing as the repo is archived
