### ISSUE TITLE
Explore using Append Blobs in Long Term Storage

### ISSUE THREAD

**Issue by bennage** [MicrosoftArchive/iot-journey#294]
[Append Blobs](http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/13/introducing-azure-storage-append-blob.aspx) seem to be a better match for the type of work we are doing in the .[NET event processor for long-term storage](https://github.com/mspnp/iot-journey/tree/master/src/LongTermStorage/DotnetEventProcessor).

Let's do some research and spiking to see what is involved in replacing our block blobs with append blobs.

**Comment by hveiras** [comment]
https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx

The main difference id that AppendBlob does not expose anything about the number of blocks it has internally nor it provides an equivalente method for DownloadBlockListAsync() which we are using to get the id's count.

As the same restriction apply to this blobs (4 MB X 50,000 blocks) we may need to store the count in a separate "Metadata" blob taking care of the possible concurrency issues.

**Comment by bennage** [comment]
The current implementation avoids concurrency issues by having a single blob per partition. If an instance of an event processor can acquire a lease on a partition. I don't recall what we were doing with `DownloadBlockListAsync`, since that does imply that we are continuing previous work.
